src/Entity/Player.php
<?php

namespace App\Entity;

use App\Util\Roulette; 
use App\Repository\PlayerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlayerRepository::class)
 */
class Player
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=12)
     */
    private $Name;

    /**
     * @ORM\Column(type="float")
     */
    private $Money;

    public $bet = 0;
    public $color = '';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getMoney(): ?float
    {
        return $this->Money;
    }

    public function setMoney(float $Money): self
    {
        $this->Money = $Money;

        return $this;
    }

    public function pickBet(){
        $total = $this->Money;

        if( $total > 1000 ){
            $percent = random_int(8,15);
            $this->bet = round( ( $total * $percent ) / 100, 2 );
        } 
        else $this->bet = $total;
    }

    public function pickColor(){
        $roulette = new Roulette;
        $this->color = $roulette->random_color();
    }

    public function win( string $color ){
        if( $this->bet > 0){
            $this->Money=round( $this->Money + ( $color === 'g' ? 14 : 1 )*$this->bet, 2 );
        }
    }

    public function lose( ){
        if( $this->bet > 0 ) $this->Money = round( $this->Money - $this->bet, 2);
    }
}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Player;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options){
        $builder->addEventListener(FormEvents::PRE_SET_DATA,
                    function (FormEvent $event){
                        $player = $event->getData();
                        $form = $event->getForm();
                        if( !$player || null === $player->getId() ){
                            $form->add('Name');
                        }
                    }
                )
                ->addEventListener(FormEvents::PRE_SET_DATA,
                    function (FormEvent $event){
                        $player = $event->getData();
                        $form = $event->getForm();
                        if( null !== $player->getId() ){
                            $form->add('Money');
                        }
                    }
        );
    }


    public function configureOptions(OptionsResolver $resolver){
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Util\Roulette; 
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class HomeController extends AbstractController
{
    /**
     * @Route ("/", name="home")
     */
    public function index( EntityManagerInterface $entityManager, Roulette $roulette ): Response
    {
        $players = $entityManager->getRepository( Player::class )->findAll();

        $baseMoney = [];// Money per player before the game starts
        foreach( $players as $player ){
            $baseMoney[$player->getId()] = "{$player->getMoney()}";
            $player->pickBet();
            $player->pickColor();
        }

        $casinoColor = $roulette->random_color();

        foreach( $players as $player ){
            if ( $casinoColor === $player->color ) $player->win( $casinoColor );
            else $player->lose();
        }

        $entityManager->flush();

        return $this->render('home/index.html.twig', [
            'players' => $players,
            'basemoney' => $baseMoney,
            'color' => $casinoColor
        ]);
    }

}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/player")
 */
class PlayerController extends AbstractController
{
    /**
     * @Route("/", name="player_index", methods={"GET"})
     */
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="player_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $player = new Player();
        $player->setMoney( 10000 );
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('player_index');
        }

        return $this->render('player/new.html.twig', [
            'player' => $player,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="player_show", methods={"GET"})
     */
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="player_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Player $player): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('player_index');
        }

        return $this->render('player/edit.html.twig', [
            'player' => $player,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="player_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Player $player): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($player);
            $entityManager->flush();
        }

        return $this->redirectToRoute('player_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {% block head %}{% endblock %}
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
        <style>
            .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
            .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        </style>
        {% endblock %}
        {% block javascripts %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% set colores = { r: 'Rojo', b: 'Negro', g: 'Verde' } %}

{% block head %}
<meta http-equiv="refresh" content="180">
{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1> Bienvenido al Casino Ruleta</h1>

    $Ruleta-><a href="{{ path('home') }}"> Girar() </a>
    <ul>
        <li>
            El color ganador es  
            {% for k,v in colores|filter( (v,k) => k == color) %}
                {{ v }} 
            {% endfor %}
        </li>
        {% for player in players %}
        <li>
            El jugador {{ player.name }} inicia con 
            {% for k,v in basemoney|filter((v,k) => k == player.id) %} 
                ${{v}} 
            {% endfor %},  
            Apuesta ${{ player.bet }} al Color
            {% for k,v in colores|filter( (v,k) => k == player.color) %}
                {{ v }}. 
            {% endfor %}
            <br>
            Dinero total despúes de la ronda: ${{player.money}}.
        </li>
        {% else %}
        <li>No players registered</li>
        {% endfor %}
    </ul>
    <a href="{{ path('player_index') }}">Lista de Jugadores</a>
</div>
{% endblock %}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn">Delete</button>
</form>

templates/player/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Editar Jugador</h1>
    <h3>{{ player.name }}</h3>
    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('player/_delete_form.html.twig') }}
    <a href="{{ path('player_index') }}">back to list</a>
</div>
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player index{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Indice de jugadores</h1>
        <a href="{{ path('home') }}"> Jugar Ruleta </a>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Dinero</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
            {% for player in players %}
                <tr>
                    <td>{{ player.id }}</td>
                    <td>{{ player.Name }}</td>
                    <td>{{ player.Money }}</td>
                    <td>
                        <a href="{{ path('player_show', {'id': player.id}) }}">ver</a>
                        <a href="{{ path('player_edit', {'id': player.id}) }}">editar</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">No hay jugadores registrados</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{{ path('player_new') }}">Añadir jugador</a>
    </div>

{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a href="{{ path('player_index') }}">back to list</a>
</div>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Player</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ player.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ player.Name }}</td>
            </tr>
            <tr>
                <th>Money</th>
                <td>{{ player.Money }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('player_index') }}">back to list</a>

    <a href="{{ path('player_edit', {'id': player.id}) }}">edit</a>

    {{ include('player/_delete_form.html.twig') }}
</div>
{% endblock %}